name: Static CI
on:
  push:
    branches: [ "main" ]
jobs:
 Deploy:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v2
      
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app
          path: ./dist

      - name: Copy files to server  
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }} 
          source: "./dist"
          target: "/home/ubuntu"


      - name: Install Nginx and Copy code to /var/www/html
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |

            sudo apt update && sudo apt upgrade -y
            echo "Successful Cache Update"
            sudo apt install nginx -y
            echo "Successful Nginx Installation"
            git clone https://github.com/GerromeSieger/Static-Site.git
            sudo systemctl start nginx
            sudo cp -r Static-Site/* /var/www/html
            sudo systemctl restart nginx

#hope 